@extends('layouts.app')

@section('title', 'Admin Workspace | Campus Scheduler')

@section('content')
<section class="cs-hero"><h1>Admin workspace</h1><p>Keep people, spaces, and requests moving through one clear queue.</p></section>
<div class="cs-layout">
  <div class="cs-form-grid">
    <section class="cs-panel"><h2>Accounts awaiting review</h2><div class="cs-table-wrap"><table class="cs-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($pendingUsers as $user)<tr><td><strong>{{ $user->name }}</strong><br><small>{{ $user->user_id }}</small></td><td>{{ ucfirst($user->role) }}</td><td><span class="cs-status cs-status-pending">Pending</span></td><td class="cs-actions"><form method="POST" action="{{ route('admin.users.decide', $user) }}" style="display:inline">@csrf @method('PATCH')<input type="hidden" name="status" value="approved"><button class="cs-button" type="submit">Approve</button></form><form method="POST" action="{{ route('admin.users.decide', $user) }}" style="display:inline">@csrf @method('PATCH')<input type="hidden" name="status" value="rejected"><button class="cs-button cs-button-warning" type="submit">Deny</button></form><form method="POST" action="{{ route('admin.users.delete', $user) }}" style="display:inline">@csrf @method('DELETE')<button class="cs-button cs-button-danger" type="submit">Delete</button></form></td></tr>@empty<tr><td colspan="4">No pending accounts.</td></tr>@endforelse</tbody></table></div></section>
    <section class="cs-panel"><h2>Booking requests</h2><div class="cs-table-wrap"><table class="cs-table"><thead><tr><th>Request</th><th>Date</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($pendingBookings as $booking)<tr><td><strong>{{ $booking->resource->name }}</strong><br>{{ $booking->user->name }} · {{ $booking->purpose }}</td><td>{{ $booking->date }}<br>{{ $booking->start_time }} - {{ $booking->end_time }}</td><td><span class="cs-status cs-status-pending">Pending</span></td><td class="cs-actions"><form method="POST" action="{{ route('admin.bookings.decide', $booking) }}" style="display:inline">@csrf @method('PATCH')<input type="hidden" name="status" value="approved"><button class="cs-button" type="submit">Approve</button></form><form method="POST" action="{{ route('admin.bookings.decide', $booking) }}" style="display:inline">@csrf @method('PATCH')<input type="hidden" name="status" value="rejected"><button class="cs-button cs-button-danger" type="submit">Decline</button></form></td></tr>@empty<tr><td colspan="4">No pending booking requests.</td></tr>@endforelse</tbody></table></div></section>
    <section class="cs-panel"><h2>Resources</h2><form method="POST" action="{{ route('admin.resources.store') }}" class="cs-form-grid cs-two-col">@csrf<input class="cs-input" name="name" placeholder="Resource name" required><select class="cs-select" name="type" required><option value="room">Room</option><option value="lab">Laboratory</option><option value="facility">Facility</option><option value="equipment">Equipment</option></select><input class="cs-input" name="location" placeholder="Location"><input class="cs-input" name="capacity" type="number" min="1" placeholder="Capacity"><button class="cs-button" type="submit">Add resource</button></form><div class="cs-table-wrap"><table class="cs-table"><tbody>@foreach($resources as $resource)<tr><td><strong>{{ $resource->name }}</strong><br><small>{{ strtoupper($resource->type) }} · {{ $resource->location }}</small></td><td class="cs-actions"><form method="POST" action="{{ route('admin.resources.delete', $resource) }}">@csrf @method('DELETE')<button class="cs-button cs-button-danger" type="submit">Delete</button></form></td></tr>@endforeach</tbody></table></div></section>
  </div>
  <aside class="cs-form-grid"><section class="cs-panel"><h2>Global notice</h2><form method="POST" action="{{ route('admin.notifications.store') }}" class="cs-form-grid">@csrf<label>Title<input class="cs-input" name="title" required></label><label>Message<textarea class="cs-textarea" name="message" rows="5" required></textarea></label><button class="cs-button" type="submit">Publish to everyone</button></form></section><section class="cs-panel"><h2>Recent notices</h2>@forelse($notifications as $notification)<div class="cs-notice"><strong>{{ $notification->title }}</strong><span>{{ $notification->message }}</span></div>@empty<p>No notices published.</p>@endforelse</section></aside>
</div>
@endsection
